# Generated by Django 3.2.20 on 2023-08-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_treet_address_1',
            new_name='default_street_address_1',
        ),
    ]
