# Generated by Django 3.2.20 on 2023-09-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_default_treet_address_1_userprofile_default_street_address_1'),
        ('consignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='profiles.userprofile'),
        ),
    ]
