# Generated by Django 3.2.20 on 2023-09-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230820_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_1_url',
        ),
    ]
